#!/usr/bin/env bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}



#Autostart applications
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
pkill -u $USER '^picom$'
picom --config $HOME/.config/herbstluftwm/picom.conf &
sxhkd -c ~/.config/herbstluftwm/sxhkd/sxhkdrc &
numlockx on &
changewallpaper &
run synergy &
flameshot &
nm-applet &
blueman-applet &
dunst &
run macchatgpt &


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

xsetroot -solid '#000000'
xsetroot -cursor_name left_ptr &


#herbstluftwm start
hc() {
    herbstclient "$@"
}

hc emit_hook reload

# KEYBINDINGS
# remove all existing keybindings
hc keyunbind --all

Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-x quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-q close
hc keybind $Mod-q close


#reload sxhkd:
hc keybind $Mod-Shift-s  pkill -USR1 -x sxhkd

# MOVEMENTS

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients to ... on single Monitor
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right



# FRAMES

# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode
# remove frame
hc keybind $Mod-x remove

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep


# focus on ...
hc keybind $Mod-Up   cycle_monitor
hc keybind $Mod-Tab         cycle
hc keybind $Mod1-Tab   use_index +1 --skip-visible
hc keybind $Mod-i jumpto urgent



# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize




tag_names=( {1..10} )
#tag_names=("Web" "Chat" "Edit" "Meld" "Vb" "Mail" "Video" "Image" "Files" "Music")
#tag_names=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")

#keys to press to get to the tags
#Qwerty
tag_keys=( {1..9} 0 )


hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    # horizontal tiling as standard
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done


# layouting
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max grid    \
               , cycle_layout +1



# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#ef6b7b'
hc set frame_border_normal_color '#4ec2e8'
#hc set frame_bg_normal_color '#2f343f'
#hc set frame_bg_active_color '#2f343f'
hc set frame_active_opacity 20
hc set frame_normal_opacity 0
hc set frame_bg_transparent 0
#hc set frame_transparent_width 0
hc set frame_gap 8
hc set frame_padding 0
hc set frame_border_width 2

hc attr theme.active.color '#ef6b7b'
hc attr theme.normal.color '#2f343f'
hc attr theme.urgent.color '#f59335'
#hc attr theme.background_color '#2f343f'
#hc attr theme.inner_color black
hc attr theme.floating.outer_color '#a1d569'
#hc attr theme.active.inner_color '#a1d569'
#hc attr theme.active.outer_color '#a1d569'
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.inner_width 0

hc set always_show_frame 0
hc set window_gap 8
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1



# RULES
hc unrule -F
hc rule focus=on # normally focus new clients


#assign applications to workspaces or tags
hc rule class=discord tag=10 focus=on switchtag=on
hc rule class=Hexchat tag=10 switchtag=on focus=on
hc rule class~'(Navigator|Mercury Browser|qutebrowser)' tag=2 switchtag=on pseudotile=on
hc rule class~'(Subl|code|Code)' tag=3 switchtag=on focus=on pseudotile=on
hc rule class=vlc tag=6 focus=on switchtag=on
hc rule class=Virt-manager tag=7 floating=on pseudotile=on
hc rule class=Joplin tag=8 switchtag=on pseudotile=on
hc rule class=koodo-reader tag=8 switchtag=on pseudotile=on
hc rule class=qutebrowser tag=2 switchtag=on pseudotile=on





# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|Alacritty|Konsole|)' focus=on floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule windowrole=xfce4-terminal-dropdown floating=on


# unlock, just to be sure
hc unlock



# do multi monitor setup here, e.g.:
hc detect_monitors
hc pad 0 30
hc pad 1 30

bool tabbed_max = true
hc rule floatplacement=smart




#launching polybar
~/.config/herbstluftwm/panel.sh
