#! /bin/bash

xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &
~/.config/bspwm/polybar/launch.sh &
numlockx on &
changewallpaper &
run synergy &
flameshot &
nm-applet &
blueman-applet &
dunst &
pkill -u $USER '^picom$'
picom --config $HOME/.config/herbstluftwm/picom.conf &


# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

xrandr --output DP-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI-1 --mode 1920x1080 --pos 1920x0 --rotate normal --output DVI-D-1 --off --output DVI-I-1 --off

/usr/libexec/polkit-gnome-authentication-agent-1 &
#deckmaster -deck ~/.config/deck/main.deck &
#[ ! -s ~/.config/mpd/pid ] && mpd &
#clipmenud &

bspc monitor DP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 10 





bspc config border_width 3
bspc config top_padding 40
bspc config bottom_padding 2
bspc config normal_border_color "#2f343f"
bspc config active_border_color "#c0caf5"
bspc config focused_border_color "#bb9af7"
bspc config presel_feedback_color "#7aa2f7"
bspc config left_padding 2
bspc config right_padding 2
bspc config window_gap 8

bspc config split_ratio 0.55
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 5
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner





bspc rule -a pulse state=floating rectangle=1280x800+380+170
bspc rule -a music state=floating rectangle=1280x800+380+170
bspc rule -a ranger state=floating rectangle=1280x800+380+170
