import = ["~/.config/alacritty/fonts.yml"]
live_config_reload = true


[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true



[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
program = "/usr/bin/zsh"


[window]
opacity = 0.9

[window.padding]
x = 15
y = 15
# BEGIN WAL
[colors.primary]
background = '#161414'
foreground = '#cfcede'

[colors.cursor]
text   = '#161414' # Apply background color to color of text inside cursor
cursor = '#cfcede' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#161414' # Same as above
cursor  = '#cfcede'

[colors.search.matches]
foreground = '#161414' # Same as above
background = '#cfcede' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#90909b'
background = '#cfcede'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#161414'
red     = '#B3817F'
green   = '#38578C'
yellow  = '#5B6994'
blue    = '#718AB6'
magenta = '#A395A9'
cyan    = '#D7A7AF'
white   = '#cfcede'

[colors.bright]
black   = '#90909b'
red     = '#B3817F'
green   = '#38578C'
yellow  = '#5B6994'
blue    = '#718AB6'
magenta = '#A395A9'
cyan    = '#D7A7AF'
white   = '#cfcede'
# END WAL
